@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

choco install git
choco install notepadplusplus.install
choco install 7zip
choco install 7zip.commandline
choco install vlc
choco install python
choco install putty
choco install filezilla
choco install Console2
choco install skype
choco install meld
choco install fiddler
choco install virtualbox
choco install vim
choco install Wget
choco install windirstat
choco install curl
choco install autohotkey.portable
choco install calibre
choco install hg
choco install PDFCreator
choco install ConEmu
choco install gimp
choco install winmerge
choco install greenshot
choco install wireshark
choco install audacity
choco install screenpresso
choco install Cygwin
choco install winscp
choco install youtube-dl
choco install launchy
choco install ConsoleZ
choco install kdiff3
choco install foobar2000
choco install expresso
choco install imagemagick.app
choco install PDFXChangeViewer
choco install nmap
choco install InkScape
choco install rdcman
choco install truecrypt
choco install ilspy
choco install ffmpeg
choco install windbg
choco install dependencywalker
choco install blender
choco install procmon
choco install ilmerge
choco install ditto
choco install windowsessentials