application: incomingp2p
version: 1
api_version: 1
runtime: python27
threadsafe: no

libraries:
- name: django
  version: "1.5"
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
