
GLOBS_SEARCH_IN_LONG = ['*.py',
                   '*.pye',
                   '*.c',
                   '*.cs',
                   '*.h',
                   '*.cpp', 
                   '*.hpp', 
                   '*.cxx', 
                   '*.txx',
                   '*.hxx', 
                   'Makefile', 
                   '*.pl', 
                   '*.pm', 
                   '*.xml', 
                   '*.xsd', 
                   '*.properties',
                   '*.call-properties',
                   '*.template',
                   '*.m',
                   '*.tex',
                   'CMakeLists.txt',
                   '*.csproj',
                   '*.sln',
                   '*.txt',
                   '*.events',
                   '*.bat',
                   '*.cmd',
                   '*.csv',
                   '*.pub',
                   '*.csproj',
                   '*.csdef',
                   '*.cscfg',
                   '*.vcxproj',
                   '*.targets',
                   '*.props',
                   '*.inc',
                   '*.props',
                   '*.meta',
                   '*.markdown',
                   '*.script',
                   '*.html',
                   '*.config',
                   '*.markdown',
                   '*.meta',
                   '*.js',
                   '*.msnp24',
                   '*.m25',
                   '*.pl']
                   
GLOBS_SEARCH_IN_SHORT = ['*.py', '*.pl', '*.cs', '*.csproj', '*.sln', '*.bat', '*.cmd', '*.cpp', '*.c', '*.h', '*.hpp']

EXCLUDE_FILE_OR_PATH = [
    '.bzr',
    '.hg',
    '.git',
    '.svn',
    'node_modules']
